services:
  - type: web
    name: llm-analysis-quiz
    env: docker
    plan: starter
    branch: main
    region: oregon
    dockerfilePath: ./Dockerfile
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: SECRET_STRING
        sync: false
      - key: EMAIL_ID
        sync: false
